### ISSUE TITLE
Qwant API usage is not allowed...

### ISSUE THREAD

**Issue by finxol** [NLDev/qwant-api#9]
In case you hadn't seen, it says in the [Qwant Terms of Service](https://about.qwant.com/legal/terms-of-service/qwant-search/) that "*no reproduction of search results is authorised*" outside of the official Qwant products...
So I assume this API is forbidden by the ToS. Sorry for that, it'd be stupid to end up in legal issues because of a project like this...

The whole paragraph :
> Unless explicitly agreed otherwise, no licence to use the QWANT Application Programming Interfaces (API) is granted to the User for any use other than within the framework of the Services published by QWANT. Consequently, no collection and no reproduction of search results is authorised other than the exceptions provided for and strictly limited by law.

**Comment by NullDev** [comment]
Thank you for your concerns. 

While it might go against Qwant's ToS, it's not against the law (according to EU right). They can terminate the service anytime (since the _Terms of Service_ were allegedly violated) and I'm okay with that. If they take measures to protect the API, I will make no attempt to bypass those. Currently however, there is nothing to bypass as the API is completely public. It just isn't documented. 

All this library does, is using the very same API Endpoints the actual Qwant Website uses as well (those endpoints can be found by making a search request on the website and checking where the request goes in devtools). There is no scraping of any kind.

> _(...)_ no collection and no reproduction of search results is authorised _(...)_

There is no collection, nor reproduction. The library doesn't index any searches / search results. It queries the same API, the Qwant website queries too and returns those results on the fly. 

The code itself does not violate any copyright or intellectual properties. And breaking ToS is not a criminal offense. 

A good read about a similar matter can be found here: https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/
